import { Public_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
